"""Initial tables

Revision ID: a7f29df5eeff
Revises: 
Create Date: 2026-07-02 05:41:22.654156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f29df5eeff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_table('wishes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visitor_name', sa.String(length=100), nullable=False),
    sa.Column('wish_message', sa.String(length=300), nullable=False),
    sa.Column('photo_filename', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishes_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishes_status'))
        batch_op.drop_index(batch_op.f('ix_wishes_created_at'))

    op.drop_table('wishes')
    op.drop_table('uploads')
    # ### end Alembic commands ###
